#!/usr/bin/env node

/**
 * Figma CLI Daemon
 *
 * Maintains a persistent CDP connection to Figma Desktop for fast command execution.
 *
 * Security features:
 * - Session token authentication (X-Daemon-Token header)
 * - No CORS headers (blocks cross-origin browser requests)
 * - Host header validation (blocks DNS rebinding)
 * - Idle timeout auto-shutdown (configurable, default 10 minutes)
 */

import { createServer } from 'http';
import { readFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { FigmaClient } from './figma-client.js';

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 10 * 60 * 1000; // Default: 10 minutes

// ============ SECURITY ============

// Load session token (generated by CLI on daemon start)
const TOKEN_FILE = join(homedir(), '.outsystems-figma-cli', '.daemon-token');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[daemon] Session token loaded');
} catch {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all requests.');
}

/**
 * Validate request authentication and origin
 * Returns null if valid, or an error string if rejected
 */
function validateRequest(req) {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(localhost|127\.0\.0\.1)(:\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: Session token (blocks unauthorized local processes)
  const token = req.headers['x-daemon-token'];
  if (!SESSION_TOKEN) {
    return 'No session token configured';
  }
  if (token !== SESSION_TOKEN) {
    return 'Invalid or missing token';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

// Start the idle timer immediately
resetIdleTimer()

// CDP Client
let cdpClient = null;
let isCdpConnecting = false;
let lastHealthCheck = 0;
let lastHealthResult = false;
const HEALTH_CACHE_MS = 5000; // Cache health for 5 seconds

// ============ CDP CONNECTION ============

async function isCdpHealthy(forceCheck = false) {
  // Quick WebSocket state check (no network call)
  if (!cdpClient || !cdpClient.ws) return false;
  if (cdpClient.ws.readyState !== 1) return false;

  // Use cached result if recent (avoids constant eval calls)
  const now = Date.now();
  if (!forceCheck && now - lastHealthCheck < HEALTH_CACHE_MS) {
    return lastHealthResult;
  }

  try {
    const result = await Promise.race([
      cdpClient.eval('1'), // Simple eval, just check connection works
      new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), 5000))
    ]);
    lastHealthCheck = now;
    lastHealthResult = result === 1;
    return lastHealthResult;
  } catch {
    lastHealthCheck = now;
    lastHealthResult = false;
    return false;
  }
}

async function getCdpClient() {
  // Fast path: if we have a client with open WebSocket, use it
  if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
    return cdpClient;
  }

  // WebSocket closed, need to reconnect
  if (cdpClient) {
    console.log('[daemon] CDP WebSocket closed, reconnecting...');
    try { cdpClient.close(); } catch {}
    cdpClient = null;
    lastHealthResult = false;
  }

  // Wait if another connection attempt is in progress
  if (isCdpConnecting) {
    while (isCdpConnecting) {
      await new Promise(r => setTimeout(r, 100));
    }
    return cdpClient;
  }

  isCdpConnecting = true;
  try {
    cdpClient = new FigmaClient();
    await cdpClient.connect();
    lastHealthCheck = Date.now();
    lastHealthResult = true;
    console.log('[daemon] Connected to Figma via CDP');
  } finally {
    isCdpConnecting = false;
  }
  return cdpClient;
}

async function executeEval(code) {
  const client = await getCdpClient();
  return client.eval(code);
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  // Reset idle timer on every request
  resetIdleTimer();

  // SECURITY: No CORS headers (blocks all cross-origin browser requests)

  // Block preflight requests (browsers send OPTIONS before cross-origin POST)
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Health check
  if (req.url === '/health') {
    const cdpHealthy = await isCdpHealthy();

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: cdpHealthy ? 'ok' : 'disconnected',
      cdp: cdpHealthy,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Force reconnect
  if (req.url === '/reconnect') {
    try {
      if (cdpClient) {
        try { cdpClient.close(); } catch {}
        cdpClient = null;
      }
      await getCdpClient();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'reconnected' }));
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      const MAX_RETRIES = 2;
      let lastError;

      for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
          const { action, code, jsx, jsxArray } = JSON.parse(body);
          let result;

          const execWithTimeout = async (fn) => {
            return Promise.race([
              fn(),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error('Execution timeout')), 60000)
              )
            ]);
          };

          switch (action) {
            case 'eval':
              result = await execWithTimeout(() => executeEval(code));
              break;
            case 'render':
              const parser = new FigmaClient();
              const renderCode = parser.parseJSX(jsx);
              result = await execWithTimeout(() => executeEval(renderCode));
              break;
            case 'render-batch':
              const batchParser = new FigmaClient();
              result = [];
              for (const j of jsxArray) {
                const batchCode = batchParser.parseJSX(j);
                result.push(await execWithTimeout(() => executeEval(batchCode)));
              }
              break;
            default:
              throw new Error(`Unknown action: ${action}`);
          }

          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ result }));
          return;
        } catch (error) {
          lastError = error;
          console.log(`[daemon] Attempt ${attempt + 1} failed: ${error.message}`);

          // Force reconnect before retry
          if (attempt < MAX_RETRIES) {
            console.log('[daemon] Reconnecting before retry...');
            try { cdpClient.close(); } catch {}
            cdpClient = null;
            await new Promise(r => setTimeout(r, 500));
          }
        }
      }

      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: lastError.message }));
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVER ============

const httpServer = createServer(handleRequest);

httpServer.listen(PORT, '127.0.0.1', () => {
  console.log(`[daemon] Figma CLI daemon running on port ${PORT}`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: token required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  if (cdpClient) cdpClient.close();
  httpServer.close(() => process.exit(0));
  // Force exit after 3 seconds if graceful shutdown hangs
  setTimeout(() => process.exit(0), 3000);
}

// Pre-connect to Figma
getCdpClient().catch(err => {
  console.log('[daemon] Waiting for Figma Desktop...');
});
